scene_filter:
  _target_: navsim.common.dataclasses.SceneFilter
  _convert_: all
  num_history_frames: 4
  num_future_frames: 10
  frame_interval: 1
  has_route: true
  max_scenes: null
  log_names:
  - 2021.05.25.14.16.10_veh-35_01100_01664
  - 2021.05.25.14.16.10_veh-35_01690_02183
  - 2021.05.25.14.16.10_veh-35_03373_03550
  - 2021.05.25.14.24.08_veh-25_03764_04034
  - 2021.05.25.14.26.37_veh-27_04122_04279
  - 2021.05.25.15.59.03_veh-30_00625_00855
  - 2021.05.25.15.59.03_veh-30_04027_04200
  - 2021.05.25.15.59.03_veh-30_04463_04606
  - 2021.05.25.17.54.41_veh-35_01905_02121
  - 2021.05.25.17.54.41_veh-35_04111_04288
  - 2021.06.03.12.02.06_veh-35_00233_00609
  - 2021.06.03.13.55.17_veh-35_02572_02855
  - 2021.06.03.13.55.17_veh-35_02866_03582
  - 2021.06.03.17.06.58_veh-35_02571_02742
  - 2021.06.03.17.06.58_veh-35_03860_03992
  - 2021.06.03.18.47.39_veh-35_00257_00492
  - 2021.06.03.18.47.39_veh-35_00503_00777
  - 2021.06.28.13.53.26_veh-26_00492_00696
  - 2021.06.28.15.02.02_veh-38_02398_02848
  - 2021.06.28.16.29.11_veh-38_03263_03766
  - 2021.06.28.20.24.43_veh-38_03385_04952
  - 2021.08.16.14.23.37_veh-45_00015_00132
  - 2021.08.30.13.45.25_veh-40_00610_00771
  - 2021.08.30.13.45.25_veh-40_00878_01104
  - 2021.08.30.13.45.25_veh-40_01116_01336
  - 2021.08.30.14.54.34_veh-40_00439_00835
  - 2021.08.30.16.16.44_veh-40_00256_00716
  - 2021.08.30.16.16.44_veh-40_00779_01088
  - 2021.08.30.16.16.44_veh-40_01099_01351
  - 2021.09.09.17.18.51_veh-48_01248_01450
  - 2021.09.16.13.53.10_veh-42_00077_00153
  - 2021.09.16.13.53.10_veh-42_00180_00342
  - 2021.09.16.13.53.10_veh-42_00860_01069
  - 2021.09.16.13.53.10_veh-42_01510_01591
  - 2021.09.16.14.39.34_veh-42_00032_00186
  - 2021.09.16.14.39.34_veh-42_00297_00935
  - 2021.09.16.14.39.34_veh-42_01111_01448
  - 2021.09.16.14.39.34_veh-42_01609_01687
  - 2021.09.16.15.12.03_veh-42_01037_01434
  - 2021.09.16.15.47.30_veh-45_01199_01391
  - 2021.09.16.16.20.27_veh-08_02435_02525
  - 2021.09.16.17.40.09_veh-45_02539_02745
  - 2021.09.16.19.12.04_veh-42_00289_00398
  - 2021.09.16.19.12.04_veh-42_01438_01677
  - 2021.09.16.19.27.01_veh-45_00472_00711
  - 2021.09.16.19.27.01_veh-45_01749_03230
  - 2021.09.16.19.49.00_veh-42_00990_01609
  - 2021.09.16.21.13.37_veh-42_00172_00347
  - 2021.09.29.14.44.26_veh-28_00238_00320
  - 2021.09.29.14.44.26_veh-28_00337_00504
  - 2021.09.29.14.44.26_veh-28_00528_00992
  - 2021.09.29.14.44.26_veh-28_01202_01296
  - 2021.09.29.14.44.26_veh-28_01331_01485
  - 2021.09.29.15.23.04_veh-28_00601_00802
  - 2021.09.29.15.23.04_veh-28_00814_01101
  - 2021.09.29.18.19.40_veh-28_00438_00833
  - 2021.09.29.18.19.40_veh-28_00844_01218
  - 2021.09.29.18.19.40_veh-28_01268_01685
  - 2021.09.29.19.02.14_veh-28_00273_00514
  - 2021.09.29.19.02.14_veh-28_00540_00917
  - 2021.09.29.19.02.14_veh-28_00964_01689
  - 2021.09.29.19.02.14_veh-28_02451_02708
  - 2021.09.29.19.02.14_veh-28_02911_03005
  - 2021.09.29.19.02.14_veh-28_03198_03360
  - 2021.10.06.07.26.10_veh-52_00006_00398
  - 2021.10.06.07.26.10_veh-52_00422_00728
  - 2021.10.06.07.26.10_veh-52_00772_00917
  - 2021.10.06.07.26.10_veh-52_00953_01126
  - 2021.10.06.07.26.10_veh-52_01245_02064
  - 2021.10.06.07.26.10_veh-52_02208_02394
  - 2021.10.06.08.16.17_veh-52_00181_00574
  - 2021.10.06.08.16.17_veh-52_00612_00782
  - 2021.10.06.08.16.17_veh-52_00922_01296
  - 2021.10.06.08.16.17_veh-52_01430_01579
  - 2021.10.06.08.16.17_veh-52_01590_01725
  - 2021.10.06.08.16.17_veh-52_01949_02501
  tokens:
  - 008d66a74c275479
  - 012ca60989175c54
  - 015011d2b73158b7
  - 01e6276eff385ea8
  - 020dee65dab453bb
  - 026e84581e0f5044
  - 02af0d9081855c54
  - 030704a9aac75776
  - 03503ef42eeb5573
  - 0372bb63e704555a
  - 03ed102b769458cd
  - 045a93a43af35fd1
  - 04703c86cf5b5a20
  - 05c1feab4b8f5957
  - 05f1c7e44f74538c
  - 05fb38ec7e175ce3
  - 06ff013e1efc5056
  - 07317a5c43a05eef
  - 0779c5aaceda51b5
  - 099e737993e15319
  - 09b2f0291de85466
  - 0bb779c3344d5b1d
  - 0d0972c70bd955cc
  - 0e479a9039ef5c10
  - 0f2b6cc2c32a51d8
  - 0f337f2c23215a9e
  - 1126dc50618d5981
  - 11bf2d4580ab5bc2
  - 1245f142241059d2
  - 1318d167bff95fb4
  - 134b10cfe7e753e6
  - 13559c5a97855007
  - 13b979f0dc215ea3
  - 141c6fbfecad5d1c
  - 1448739cbe165094
  - 1468001ef92e5109
  - 157c6c5b1b9d5608
  - 15822499ddf9515d
  - 1611f4d5c0395de4
  - 16295788c73b5d86
  - 165838dcee0152fe
  - 1661065c080c51d8
  - 1671f2a335fb5968
  - 1774308b2ce65a6b
  - 17aab91aa7585eb6
  - 17e417633368553f
  - 180e235fe7b75dbc
  - 182fe7c6dd5b5e44
  - 19585f102d0a5fb6
  - 19c99be4f21f5a0a
  - 19cd103b5ae1538e
  - 1a0f27ced7e056f6
  - 1a37d69ab5805f15
  - 1b30838ebfee5924
  - 1b439c269a83590c
  - 1bc034e245e85197
  - 1d2ce89fe79f55bd
  - 1e5912e7fc4f5451
  - 1e60548b4c00538a
  - 1ec58e13fee45a30
  - 1ed7ae84b65d52b4
  - 1f913e9b33f155c6
  - 205b6a7713b15328
  - 20e43811ef645269
  - 20eb3d1d711554a3
  - 21265a3838ee5a46
  - 21cd282d8b27526f
  - 221eebe0f41d5e04
  - 229e86f19e7d5ced
  - 22dde440a0c35d31
  - 23502259fe7450ea
  - 237b75204e495145
  - 23f0187033d658d9
  - 24108688ab4856ab
  - 25cdf7dee0d25a66
  - '2633340672525214'
  - 267005afb82050c1
  - 27ff47ea8aea59cf
  - 281510a734895f33
  - 284fd8dedc2c59a4
  - 294ea882f7ba5d71
  - 2ad650691b5d58f0
  - 2b201c0ffa245b8b
  - 2bf7a51839cb59eb
  - 2c34a443473f5a82
  - 2d6b0679be1753dc
  - 2d8d56c6e9505e46
  - 2fb54b28d0c55807
  - 2fe345a90b6559e1
  - 2ffcc771b9375796
  - 307b5c7a59cd57b2
  - 315aedf84f9f59c3
  - 325c162902835de3
  - 32648fe3eaa45ed1
  - 32de90ab38ad568a
  - 341d69eed08a520b
  - 348680e464e15fa2
  - 349b80a3d95e5f6e
  - 351121baccc95bad
  - 3554e319cfc55fa1
  - 35ae50756b8952b9
  - 35f13a6de1575fdc
  - 371a6b4bc47d5d87
  - 38e2900d6e60513b
  - 38f1e14586bd51e3
  - 3aa02e49724c5c4b
  - 3ae2ab1099d65c2a
  - 3b34e3fd5b9e5767
  - 3ceb5afc67975881
  - 3dac4631b32d5baa
  - 3e41024d080454b5
  - 3fd83f3f2ac3592a
  - 3fea25d764c355dc
  - 40fdcf88e3265655
  - 410171a43ce453c2
  - 41a845d429a35887
  - 41f5e95324715d0e
  - 43861b94f4d959eb
  - 4459594521595a93
  - 465d43bf893d5e66
  - 47510e11da5555ed
  - 47f9e40a21f7510a
  - 48bbe3acc93450aa
  - 48c16e2d0c5f59e7
  - 490463fd7e9e5769
  - 4909b88b347c5764
  - 496770277e3e50d7
  - 49abf280107f5810
  - 49ee466685265a80
  - 49f8fc6be75f56fc
  - 4a4c046eff125fca
  - 4a7fd1bd37ed5463
  - 4af3bf4ef6f35dc7
  - 4b1073732de35303
  - 4c2d79a8bcc155bd
  - 4c321bb392105b81
  - 4c37db4893c155d2
  - 4cee76c8118b5609
  - 4e3aab178b035e85
  - 4f87ef91e3425ebc
  - 50613cf56a8d5a38
  - 50aa287e430e5ab3
  - 527460a8acda5c41
  - 53c9f25e1fda5ce0
  - 5496f69033515dd4
  - 557109eff1465e61
  - 55eed45c895852b9
  - 563f15ca855f541d
  - 567469e556cf5e6b
  - 57b4b980c94757c1
  - 594e39f9024a5835
  - 59bb570b4290572d
  - 59db265fc4cf5a41
  - 5a41a7f756c551ce
  - 5b31f501fa395990
  - 5b5be980b0815e76
  - 5be54baed8b35bd7
  - 5c57e87e3c2a5b09
  - 5c5e0e2c9d225b98
  - 5c9f3b6bfc615ad4
  - 5e4dd8c91b8453bf
  - 5ea36cebd2575b16
  - 5f124bba478c570a
  - 5f89ac40ee155a0e
  - 5fc741e3c1875ae3
  - 601c3cce2a215275
  - 60216ba3ee9557d9
  - 609d74e2399c53ad
  - 60d952f0aa505d3e
  - 610d428caeb35b9e
  - 6139b7811b87514b
  - 624182d3de8255d8
  - 63372e43883c5a85
  - 6352864cf9f95bb8
  - 643b177aa4235fe7
  - 649fc97f62be5ebb
  - 64d046ec9cee51d4
  - 66225fc71bd35554
  - 66368e570f415f55
  - 66a2be8354ba5535
  - 66c9f19c11615415
  - 66f664c031765c74
  - 671da9103fe05141
  - 67628d15c5b45860
  - 67905d7b4c3e564e
  - 6970d8207923563a
  - 69a4a5913bfc5d5d
  - 69f80a41cbaa5c1b
  - 6aeafad06d0055ba
  - 6afb5356f35b547c
  - 6b9c9cf543b25944
  - 6bc77f3b97795470
  - 6c578cebcf47592b
  - 6d2fdf97f60654af
  - 6d3bb2ecca3e54b4
  - 6ea198f259b85e49
  - 6ec94adda61e5483
  - 6f31e863bab65c62
  - 6fdea0636809523e
  - 7032d9dfb6415988
  - 70615adb309b596a
  - 70d9aa5a289157c2
  - 714710682a6954fd
  - 71aea26de05f5b5d
  - 71d723610abd5f16
  - 729f20a59c075d82
  - 73c600dba1795b0c
  - 74499565609f56ad
  - 74cf2bc3433f59dd
  - 786c49b2f19f54c0
  - 7a6d3719323a5188
  - 7ab9788ed4bb5bda
  - 7ac633604a3c572d
  - 7b6efdd222ca5777
  - 7c7c063205ec5f3c
  - 7c7e92d50f92564b
  - 7edfabe116e25844
  - 7f19b2fd14435b73
  - 804236dcfffa523e
  - 80c159e90ae755f3
  - 8140728e0011561d
  - 821f5be699cd5942
  - 82e1485de4fa5b71
  - 8339579a512e5ac0
  - 834a7c22e2c55c71
  - 837ce609a8ec58e9
  - 85782dccb8715e91
  - 85da27c3381e5e63
  - 85dba97943515cbd
  - 85dd8df144d6551e
  - 861a8feb26275bd1
  - 8685d4420d83534f
  - 8847def0336a54a1
  - 89b190b36cd75ce9
  - 8a67627289225991
  - 8a6d53a0e36a599d
  - 8a81c8c3f87b5c9c
  - 8b413245a4055519
  - 8c240d53cf9e5c6a
  - 8c639d319c5e5e20
  - 8cef0a91cc225732
  - 8cfce2bdf24a5260
  - 8d86cfd038145f2a
  - 8f224f01713a5376
  - 8f8ce43e73ab5045
  - 90335cc20a755637
  - 9095dbedac905e58
  - 90e143b64aa15442
  - 9243ca15a76e552f
  - 92c38e520e515a8a
  - 931c9ec2bfa55d47
  - 93a5e1de2d185374
  - 93ded00411ba5505
  - 95809cb5fc4a549f
  - 9587d6ea0a8e518f
  - 964c8941cfe558bb
  - 964f8f7263c0562f
  - 97c8e9ca10ba5a69
  - 97e2daddecd557a4
  - 98c7a48dd75052ab
  - 9a00d37375a95d7e
  - 9a0b762c08af59f8
  - 9a4e8cacd6095527
  - 9aa76ff06fd153d8
  - 9abcb094fcef5f84
  - 9acaaa1400115088
  - 9b4a82c95856552f
  - 9be9c9c84b625515
  - 9cfdfd9619325a79
  - 9d010e744f5b5c3a
  - 9e7d2e400b4d5e26
  - 9ea456b1af1758d6
  - 9f6ae3dae4585cef
  - 9fcf3a5f4d495b70
  - 9fe2a67d11ff55f2
  - a031a7d531295e92
  - a04f86a92daf50ba
  - a117c55be29c5412
  - a1adc0fae78f5a3f
  - a25c5a2632f952d7
  - a27875deccc151e0
  - a2e68628420f5c97
  - a38bd3c8068d5ebb
  - a4004f6529cf511e
  - a412624e363853f0
  - a472c2f69a3456f3
  - a4a6338966735427
  - a50a5cf062ed5135
  - a51fda3f10da5432
  - a5725e330a565f84
  - a69eba54eedd5a64
  - a7eedd1eb65b51bf
  - a85ffd3bc9775adb
  - a87b2701a5c558f4
  - a8f83a28e925555d
  - a9af1e73c9575428
  - aa702a3bfb615886
  - aaa52295ba6e5daf
  - acd1fd0b50b659c8
  - acfe9f2fe77c5b79
  - ada676e1203d5ad7
  - aedd14aa2f3452c3
  - afb6f330e8665731
  - b04064e074f55bb0
  - b0aa550f818f52a0
  - b11d39291cd55ed7
  - b1e0acd51fbf5895
  - b2bf491595815a21
  - b2c9c066dc43545b
  - b3056d1269ae5df9
  - b3211f9908a45786
  - b3b3a0cc7dec50a0
  - b523d101fb0958c3
  - b555e2488dc7531e
  - b74b5977823b527a
  - b77b4b6eb149553f
  - b7d4918c77945775
  - b8819562a6ed5096
  - b8b67fccb642589b
  - b8d4a8d9b16859d4
  - b9ca1e41206e5a03
  - ba8b30ba37d05ed6
  - bac42a73c49d5589
  - bca8b9c053845df8
  - bd646d9caaef57d8
  - bdae4b23337b5834
  - beaa12171da45b46
  - bf2eac0b47c55db7
  - bf525da8b60559fc
  - c013fdf3f7505fc2
  - c06773e2267b568e
  - c0b8f52197ac558c
  - c0fb4281da785582
  - c1e612a123d059d7
  - c1e88ed6895053e8
  - c2e656fd89675b6c
  - c370f836e3275da4
  - c38e0ed510f45ed0
  - c3c375ac03435ee2
  - c3d453408f7a5b44
  - c460ec097ed958a2
  - c46b2546f3565375
  - c4b1d4fabd315035
  - c51794fe27365574
  - c5510354351d5d5e
  - c602d7c53cdb500c
  - c651cbad634b54f5
  - c65c265780365bb1
  - c6be203c41a155e4
  - c7af3cc6ee42577f
  - c849fb5493be5a70
  - c8ba106036ea56b1
  - cb8b1f36617c50d4
  - cbb561f30e295903
  - cc9c17cee08d59ca
  - cd8713b912495b6d
  - cdba5e3c59af59da
  - cdd98520c4e95450
  - ceb5b3df40105f05
  - cefece29b7b459fa
  - cf602364e14b563d
  - cfafe7fdd6b15b4d
  - cfd1452f415d5b07
  - d063f70ffb44513e
  - d0c31f4b85ea5028
  - d10f3128649054ef
  - d113b39be843564f
  - d1f968b127ae5f25
  - d2fa9bb30cae5e4d
  - d3351ac6f9185249
  - d34b1a7834a35883
  - d3999ba1a6b9527a
  - d49c7581099d56be
  - d4f46232d69d5d16
  - d639c104b63e568d
  - d6b5646287065fa8
  - d7193cbff1cd58e2
  - d79128ba24155262
  - d7928caf300452e2
  - d7cc45e58d175329
  - d8052747bb57544b
  - d849d3813e3052d0
  - d85c679f79b552ae
  - d92297ffbf655d53
  - d94aa4b0e05e5be9
  - d9721a19dde7507a
  - da0aac1f6c225eca
  - dadfddb20a29587d
  - dc12fe40cbbb5b3f
  - dc376531664b51b8
  - dd71dee142f05d7d
  - dd79f9aa92105761
  - dd9646cfa6935fae
  - de354f243fa157ec
  - de756f627de855fd
  - df11795878cb5419
  - dfd5770faffa5ba7
  - e06452718ec757c6
  - e2fcfbb473e95bc8
  - e37f3f28d9bb5445
  - e3aacc0a542d5e15
  - e4237030b1b75a8d
  - e450c08eafcf5b91
  - e5e0c85236f95d91
  - e5e21bbf8d665374
  - e63b6dfddfc855da
  - e66d21ee45e65dac
  - e6dc564e1a3a588e
  - e6e4e254f1c55405
  - e7ca264a0dd359f3
  - e8ad4904c3d658bd
  - e982719caf425a10
  - ea34282dc63d5a9a
  - ea57ba531b9f5599
  - ead2f3a4f1ad58ac
  - eb48efcbc80f59b7
  - eb72736f2edf5380
  - eba2b9d63f5b5ae8
  - ebad44bb4ab65707
  - ebf97a584bcb556e
  - eccf91e1e1635acf
  - ed19f6a36af757b7
  - ed31f41d4b2c5e33
  - ed3da5aa48d15354
  - edb0dbd58be650f3
  - ee91209e45fe5141
  - f0d1419c24b85651
  - f1041299a1a059f5
  - f15b26c87a0e557d
  - f2291b8766215c41
  - f34ebf09b5515de1
  - f3d2d8c177b95556
  - f419cea88ed9500b
  - f4d95a784b725915
  - f4da372227475285
  - f6d575d8e0a45772
  - f790e64181a15f5a
  - f841083805af5242
  - f9d395a43f2550dd
  - faf8f696fd8a5298
  - fb21dbec77535015
  - fb35180af57e571f
  - fc2a258a2dc153a8
  - fc8a398075265f44
  - fd676fd01e475e33
  - fddb0bdd1d7f53e0
  - fe5298731e0f5a6c
  - fef473f296d15eee
  - ff3e6f394fea51bf
  - ff9d7c14934b541e
worker:
  _target_: navsim.planning.utils.multithreading.worker_ray_no_torch.RayDistributedNoTorch
  _convert_: all
  master_node_ip: null
  threads_per_node: null
  debug_mode: false
  log_to_driver: true
  logs_subdir: logs
  use_distributed: false
split: test
distributed_timeout_seconds: 7200
selected_simulation_metrics: null
verbose: false
logger_level: info
logger_format_string: null
max_number_of_workers: null
gpu: true
experiment_name: eval_navhard
navsim_log_path: ${oc.env:OPENSCENE_DATA_ROOT}/navsim_logs/${split}
sensor_blobs_path: /home/harsh/dataset/navhard_two_stage/sensor_blobs
date_format: '%Y.%m.%d.%H.%M.%S'
experiment_uid: ${now:${date_format}}
output_dir: ${oc.env:NAVSIM_EXP_ROOT}/${experiment_name}/${experiment_uid}
proposal_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: all
  num_poses: 40
  interval_length: 0.1
simulator:
  _target_: navsim.planning.simulation.planner.pdm_planner.simulation.pdm_simulator.PDMSimulator
  _convert_: all
  proposal_sampling: ${proposal_sampling}
scorer:
  _target_: navsim.planning.simulation.planner.pdm_planner.scoring.pdm_scorer.PDMScorer
  _convert_: all
  proposal_sampling: ${proposal_sampling}
  config:
    _target_: navsim.planning.simulation.planner.pdm_planner.scoring.pdm_scorer.PDMScorerConfig
    _convert_: all
    progress_weight: 5.0
    ttc_weight: 5.0
    comfortable_weight: 2.0
    driving_direction_horizon: 1.0
    driving_direction_compliance_threshold: 2.0
    driving_direction_violation_threshold: 6.0
    stopped_speed_threshold: 0.005
    progress_distance_threshold: 5.0
agent:
  _target_: navsim.agents.SeerDrive.SeerDrive_agent.SeerDriveAgent
  _convert_: all
  config:
    _target_: navsim.agents.SeerDrive.configs.default.SeerDriveConfig
    _convert_: all
  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: all
    time_horizon: 4
    interval_length: 0.5
  checkpoint_path: /home/harsh/SeerDrive/checkpoints/seerdrive_checkpoint.ckpt
  lr: 0.0002
metric_cache_path: /home/harsh/SeerDrive/exp/metric_cache
